### ISSUE TITLE
Add phone number

### ISSUE THREAD

**Issue by onedebos** [onedebos/naija-faker#3]
Generate phone numbers based on mobile network

**Comment by nikhil-chaurasia14** [comment]
@onedebos 
+234-802-5558-1, is this a valid phone number? If not, then what is the valid format?

**Comment by onedebos** [comment]
Hello Nikhil,

A valid phone number is +234-805(PREFIX)-456-7890.

See a list of prefixes valid here.

https://en.wikipedia.org/wiki/Telephone_numbers_in_Nigeria#Mobile_phone_network_prefixes_[1]
