### ISSUE TITLE
Address

### ISSUE THREAD

**Issue by onedebos** [onedebos/naija-faker#4]
Add house address

**Comment by mayankbucha** [comment]
@onedebos  how many address are needed?

**Comment by onedebos** [comment]
Hi Maynak. As many Nigerian addresses as possible so that we can generate a
wide variety of data.

Preferably, addresses should be broken down into:

House number,
Street Address,
City

**Comment by mayankbucha** [comment]
Great!

**Comment by onedebos** [comment]
@mayankbucha Thank you! Don't forget to update the `authors` section of the Readme with your details.
